---
name: 'Build'

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "17 6 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Build
        run: |
          npm install
          npm run build

      - name: HACS build validation
        uses: "hacs/action@21.12.1"
        with:
          category: "plugin"

          # Don't attempt to load into HACS (as it loads the release, not the
          # build).
          ignore: "hacs"
