---
name: 'Build'

on:
  push:
    branches:
      - master
      - main
      - dev
  pull_request:
  schedule:
    - cron: "17 6 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          npm install
          npm run build

  hacs:
    runs-on: "ubuntu-latest"
    name: HACS
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v2.3.4"

      - name: HACS validation
        uses: "hacs/action@21.2.2"
        with:
          category: "plugin"
