---
name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node and Yarn
        uses: volta-cli/action@v3

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build the files
        run: yarn run build

      - name: Zip the files
        uses: montudor/action-zip@v1
        with:
          args: cd dist/ && zip frigate-hass-card.zip *

      - name: Upload files to release
        uses: svenstaro/upload-release-action@2.5.0

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*.js dist/*.zip
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true

      - name: HACS release validation
        uses: hacs/action@21.12.1
        with:
          category: plugin
