---
name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node and Yarn
        uses: volta-cli/action@v3

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build the file
        run: yarn run build

      # Upload build file to the release as an asset.
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*.js
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true

      - name: HACS release validation
        uses: "hacs/action@21.12.1"
        with:
          category: "plugin"
